# Generated by Django 3.1.2 on 2020-10-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='CalculationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoApp.calculation')),
                ('id_repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoApp.repair')),
            ],
        ),
        migrations.AddField(
            model_name='calculation',
            name='id_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoApp.car'),
        ),
    ]
